_BASE = "https://github.com/ohquebacan/OQB-BadStick-Mac/releases/download/v1.0.0/"

CATALOG = {
    # ── Install methods ──────────────────────────────────────────────────
    "badupdate": {
        "name": "BadUpdate",
        "tab": "install",
        "type": "base",
        "desc": "Exploit original — descarga archivos de ABadAvatar sin payload libre",
        "dest": "",
        "author": "Grimdoomer",
    },
    "abadavatar": {
        "name": "ABadAvatar",
        "tab": "install",
        "type": "auto",
        "api_url": "https://api.github.com/repos/shutterbug2000/ABadAvatar/releases/latest",
        "fallback_url": "https://github.com/shutterbug2000/ABadAvatar/releases/download/vPB1.0/ABadAvatar-publicbeta1.0.zip",
        "asset_pattern": ".zip",
        "dest": "",
        "author": "shutterbug2000",
        "desc": "Requiere dashboard 17559 y datos de avatar instalados",
    },
    "badavatarhdd": {
        "name": "BadAvatarHDD",
        "tab": "install",
        "type": "auto",
        "api_url": "https://api.github.com/repos/shutterbug2000/ABadAvatar/releases/latest",
        "fallback_url": "https://github.com/shutterbug2000/ABadAvatar/releases/download/vPB1.0/ABadAvatar-publicbeta1.0.zip",
        "asset_pattern": ".zip",
        "dest": "",
        "author": "shutterbug2000",
        "desc": "Variante HDD — para consolas sin tarjeta de memoria",
    },
    "abadmemunit": {
        "name": "ABadMemUnit",
        "tab": "install",
        "type": "auto",
        "api_url": "https://api.github.com/repos/shutterbug2000/ABadMemUnit/releases/latest",
        "fallback_url": None,
        "asset_pattern": ".zip",
        "dest": "",
        "author": "shutterbug2000",
        "desc": "Alternativa si ABadAvatar no funciona en tu consola",
    },
    # ── Patches ──────────────────────────────────────────────────────────
    "xeunshackle": {
        "name": "XeUnshackle",
        "tab": "install",
        "type": "auto",
        "api_url": "https://api.github.com/repos/Byrom90/XeUnshackle/releases/latest",
        "fallback_url": "https://github.com/Byrom90/XeUnshackle/releases/download/v1.03/XeUnshackle-v1.03.zip",
        "asset_pattern": ".zip",
        "dest": "",
        "author": "Byrom90",
        "desc": "Más compatible con plugins y stealth servers",
    },
    "freemyxe": {
        "name": "FreeMyXe",
        "tab": "install",
        "type": "auto",
        "api_url": "https://api.github.com/repos/InvoxiPlayGames/FreeMyXe/releases/latest",
        "fallback_url": "https://github.com/InvoxiPlayGames/FreeMyXe/releases/download/v1.1/FreeMyXe-v1.1.zip",
        "asset_pattern": ".zip",
        "dest": "",
        "author": "InvoxiPlayGames",
        "desc": "Alternativa open-source a XeUnshackle",
    },
    # ── Dashboards ───────────────────────────────────────────────────────
    "aurora": {
        "name": "Aurora",
        "tab": "dashboards",
        "type": "auto",
        "direct_url": _BASE + "Aurora.zip",
        "dest": "Dashboards/Aurora",
        "author": "Phoenix Team",
        "desc": "Dashboard más popular para Xbox 360 homebrewado",
        "color": "#107C10",
    },
    "freestyle": {
        "name": "Freestyle Dash",
        "tab": "dashboards",
        "type": "auto",
        "direct_url": _BASE + "Freestyle.zip",
        "dest": "Dashboards/Freestyle",
        "author": "xboxUnity",
        "desc": "Dashboard alternativo con soporte de skins",
        "color": "#1a3a6a",
    },
    "emerald": {
        "name": "Emerald",
        "tab": "dashboards",
        "type": "auto",
        "direct_url": _BASE + "Emerald.zip",
        "dest": "Dashboards/Emerald",
        "author": "Unknown",
        "desc": "Dashboard alternativo con interfaz minimalista",
        "color": "#1a6a3a",
    },
    "xexdash": {
        "name": "XeXDash",
        "tab": "dashboards",
        "type": "manual",
        "dest": "Dashboards/XeXDash",
        "author": "Unknown",
        "desc": "Dashboard clásico de la escena homebrew",
        "color": "#4a3a1a",
    },
    "xexloader": {
        "name": "XeXLoader",
        "tab": "dashboards",
        "type": "auto",
        "direct_url": _BASE + "XeXLoader.zip",
        "dest": "Dashboards/XeXLoader",
        "author": "Unknown",
        "desc": "Launcher simple de archivos XEX",
        "color": "#3a1a4a",
    },
    "ingeniouxd": {
        "name": "IngeniouX",
        "tab": "dashboards",
        "type": "auto",
        "direct_url": _BASE + "IngeniouX.zip",
        "dest": "Dashboards/IngeniouX",
        "author": "Unknown",
        "desc": "Dashboard moderno con interfaz actualizada",
        "color": "#1a4a6a",
    },
    "xenu": {
        "name": "Xenu",
        "tab": "dashboards",
        "type": "auto",
        "direct_url": _BASE + "Xenu.zip",
        "dest": "Dashboards/Xenu",
        "author": "Unknown",
        "desc": "Dashboard ultraminimalista para consolas homebrewadas",
        "color": "#3a3a3a",
    },
    "viper360": {
        "name": "Viper360",
        "tab": "dashboards",
        "type": "auto",
        "direct_url": _BASE + "Viper360.zip",
        "dest": "Dashboards/Viper360",
        "author": "Unknown",
        "desc": "Dashboard alternativo con gestor de juegos integrado",
        "color": "#6a1a1a",
    },
    # ── Homebrew ─────────────────────────────────────────────────────────
    "god_unlocker": {
        "name": "GOD Unlocker",
        "tab": "homebrew",
        "type": "auto",
        "direct_url": _BASE + "GOD.Unlocker.zip",
        "dest": "Homebrew/GOD Unlocker",
        "author": "Unknown",
        "desc": "Desbloquea archivos GOD de juegos instalados",
    },
    "xm360": {
        "name": "XM360",
        "tab": "homebrew",
        "type": "auto",
        "direct_url": _BASE + "XM360.zip",
        "dest": "Homebrew/XM360",
        "author": "xboxUnity",
        "desc": "Gestor de contenido multimedia para Xbox 360",
    },
    "ffplay": {
        "name": "FFPlay",
        "tab": "homebrew",
        "type": "auto",
        "direct_url": _BASE + "FFPlay.zip",
        "dest": "Homebrew/FFPlay",
        "author": "Unknown",
        "desc": "Reproductor multimedia basado en FFmpeg",
    },
    "hddx_fixer": {
        "name": "HDD Compatibility Fixer",
        "tab": "homebrew",
        "type": "auto",
        "direct_url": _BASE + "HDDx.Fixer.zip",
        "dest": "Homebrew/HDD Compatibility Fixer",
        "author": "Unknown",
        "desc": "Herramienta de reparación y mantenimiento de HDD",
    },
    "xpg_chameleon": {
        "name": "XPG Chameleon",
        "tab": "homebrew",
        "type": "auto",
        "direct_url": _BASE + "XPG.Chameleon.zip",
        "dest": "Homebrew/XPG Chameleon",
        "author": "Unknown",
        "desc": "Gestor y editor de perfiles de jugador Xbox 360",
    },
    "xna_offline": {
        "name": "XNA Offline",
        "tab": "homebrew",
        "type": "auto",
        "direct_url": _BASE + "XNA.Offline.zip",
        "dest": "Homebrew/XNA Offline",
        "author": "Unknown",
        "desc": "Soporte XNA para juegos indie sin conexión a internet",
    },
    "nxe2god": {
        "name": "NXE2GOD",
        "tab": "homebrew",
        "type": "auto",
        "direct_url": _BASE + "NXE2GOD.zip",
        "dest": "Homebrew/NXE2GOD",
        "author": "Unknown",
        "desc": "Convierte instalaciones NXE al formato GOD rip",
    },
    "nand_flasher": {
        "name": "Simple 360 NAND Flasher",
        "tab": "homebrew",
        "type": "auto",
        "direct_url": _BASE + "Flasher.zip",
        "dest": "Homebrew/Simple 360 Flasher",
        "author": "Swizzy",
        "desc": "Flasher NAND para consolas con hardware modificado",
    },
    "xell_launch": {
        "name": "Xell Launch",
        "tab": "homebrew",
        "type": "manual",
        "dest": "Homebrew/XellLaunch",
        "author": "Unknown",
        "desc": "Launcher de Xell desde la interfaz NXE",
    },
    # ── Stealth Servers ──────────────────────────────────────────────────
    "proto": {
        "name": "Proto",
        "tab": "stealth",
        "type": "auto",
        "direct_url": _BASE + "Proto.zip",
        "free": True,
        "dest": "Stealth Networks/Proto",
        "author": "freestealth.com",
        "desc": "Red stealth GRATUITA — funciona con dashboard 17559",
        "log_hint": "Configura el servidor en DashLaunch después de instalar",
    },
    "xblghost": {
        "name": "xblGhost",
        "tab": "stealth",
        "type": "manual",
        "free": True,
        "url": "https://xblghost.live",
        "dest": "Stealth Networks/xblGhost",
        "author": "xblghost.live",
        "desc": "Red stealth GRATUITA — compatible con dashboard 17559",
        "log_hint": "Descarga cliente en xblghost.live → configura en DashLaunch",
    },
    "xbls": {
        "name": "XBLS",
        "tab": "stealth",
        "type": "auto",
        "direct_url": _BASE + "XBLS.zip",
        "free": False,
        "dest": "Stealth Networks/XBLS",
        "author": "xboxstealth.net",
        "desc": "Stealth server de pago — requiere suscripción en xboxstealth.net",
    },
    "cipher": {
        "name": "Cipher",
        "tab": "stealth",
        "type": "auto",
        "direct_url": _BASE + "CipherLive.zip",
        "free": False,
        "dest": "Stealth Networks/Cipher",
        "author": "Unknown",
        "desc": "Red stealth de pago — configura credenciales en DashLaunch",
    },
    "xbguard": {
        "name": "XbGuard",
        "tab": "stealth",
        "type": "auto",
        "direct_url": _BASE + "xbGuard.zip",
        "free": False,
        "dest": "Stealth Networks/XbGuard",
        "author": "xbguard.live",
        "desc": "Stealth server de pago — requiere suscripción en xbguard.live",
    },
    "xbnetwork": {
        "name": "XbNetwork",
        "tab": "stealth",
        "type": "auto",
        "direct_url": _BASE + "xbNetwork.zip",
        "free": False,
        "dest": "Stealth Networks/xbNetwork",
        "author": "Unknown",
        "desc": "Red privada virtual de pago para Xbox 360 online",
    },
    "nfinite": {
        "name": "Nfinite",
        "tab": "stealth",
        "type": "auto",
        "direct_url": _BASE + "Nfinite.zip",
        "free": False,
        "dest": "Stealth Networks/Nfinite",
        "author": "Unknown",
        "desc": "Servicio stealth de pago y alta seguridad",
    },
    "tethered_live": {
        "name": "Tethered Live",
        "tab": "stealth",
        "type": "auto",
        "direct_url": _BASE + "TetheredLive.zip",
        "free": False,
        "dest": "Stealth Networks/Tethered Live",
        "author": "Unknown",
        "desc": "Conecta tu Xbox a Live usando tu PC como proxy",
    },
    "xbl_kyuubii": {
        "name": "XBL Kyuubii",
        "tab": "stealth",
        "type": "auto",
        "direct_url": _BASE + "XBL.Kyuubii.zip",
        "free": False,
        "dest": "Stealth Networks/XBL Kyuubii",
        "author": "Unknown",
        "desc": "Stealth alternativo de pago con cliente ligero",
    },
    # ── Plugins ──────────────────────────────────────────────────────────
    # general_plugins → Plugins.zip contains the loose XEX files (JRPC2, RPC, xbdm…)
    "general_plugins": {
        "name": "General Plugins (JRPC2, RPC, xbdm…)",
        "tab": "plugins",
        "group": "Plugins",
        "type": "auto",
        "direct_url": _BASE + "Plugins.zip",
        "dest": "Plugins",
        "author": "Various",
        "desc": "JRPC2.xex, RPC.xex, xbdm.xex, XDRPC.xex, XRPC.xex — sueltos en Plugins/",
    },
    "xbpirate": {
        "name": "xbPirate",
        "tab": "plugins",
        "group": "Plugins",
        "type": "auto",
        "direct_url": _BASE + "xbPirate.zip",
        "dest": "Plugins/xbPirate",
        "author": "Unknown",
        "desc": "Plugin de gestión y descarga de contenido",
    },
    "hiddriver360": {
        "name": "hiddriver360",
        "tab": "plugins",
        "group": "Plugins",
        "type": "auto",
        "direct_url": _BASE + "hiddriver360.zip",
        "dest": "Plugins/hiddriver360",
        "author": "Unknown",
        "desc": "Driver HID personalizado para periféricos USB",
    },
    "hvp2": {
        "name": "HvP2",
        "tab": "plugins",
        "group": "Plugins",
        "type": "auto",
        "direct_url": _BASE + "HvP2.zip",
        "dest": "Plugins/HvP2",
        "author": "Unknown",
        "desc": "Parche del hipervisor v2 para funciones avanzadas",
    },
    "fakeanim": {
        "name": "FakeAnim V0.60",
        "tab": "plugins",
        "group": "Personalización",
        "type": "auto",
        "direct_url": _BASE + "fakeAnim.zip",
        "dest": "FakeAnim",
        "author": "Unknown",
        "desc": "Personaliza las animaciones de arranque de la consola",
    },
    "x_notify": {
        "name": "X-Notify Pack",
        "tab": "plugins",
        "group": "Personalización",
        "type": "auto",
        "direct_url": _BASE + "X-Notify.Pack.zip",
        "dest": "Customization/X-Notify Pack",
        "author": "Unknown",
        "desc": "Pack de notificaciones personalizadas del sistema",
    },
    "boot_animation": {
        "name": "FakeAnim Boot Animations",
        "tab": "plugins",
        "group": "Personalización",
        "type": "auto",
        "direct_url": _BASE + "Boot.Animations.zip",
        "dest": "FakeAnim Boot Animations",
        "author": "Unknown",
        "desc": "Colección de animaciones WMV de arranque para FakeAnim",
    },
    "xbox_one_xefu": {
        "name": "Xbox One Files",
        "tab": "plugins",
        "group": "Retrocompatibilidad",
        "type": "auto",
        "direct_url": _BASE + "Xbox.One.Files.zip",
        "dest": "Backwards Compatibility/Xbox One Files",
        "author": "Unknown",
        "desc": "Archivos XEFU de compatibilidad con Xbox One",
    },
    "hacked_compat": {
        "name": "Hacked Compatibility Files",
        "tab": "plugins",
        "group": "Retrocompatibilidad",
        "type": "auto",
        "direct_url": _BASE + "Hacked.Compatibility.Files.zip",
        "dest": "Backwards Compatibility/Hacked Compatibility Files",
        "author": "Unknown",
        "desc": "Archivos de retrocompatibilidad modificados",
    },
    "xefu_spoofer": {
        "name": "XEFU Spoofer V5",
        "tab": "plugins",
        "group": "Retrocompatibilidad",
        "type": "auto",
        "direct_url": _BASE + "XEFU.Spoofer.zip",
        "dest": "Backwards Compatibility/XEFU Spoofer V5",
        "author": "Unknown",
        "desc": "Spoofer de compatibilidad Xbox One v5",
    },
    "original_compat": {
        "name": "Original Compatibility Files",
        "tab": "plugins",
        "group": "Retrocompatibilidad",
        "type": "auto",
        "direct_url": _BASE + "Original.Compatibility.Files.zip",
        "dest": "Backwards Compatibility/Original Compatibility Files",
        "author": "Unknown",
        "desc": "Archivos originales de retrocompatibilidad de Microsoft",
    },
}

# Method → effective download key mapping
METHOD_DL_MAP = {
    "badupdate":    "abadavatar",
    "badavatarhdd": "abadavatar",
    "abadavatar":   "abadavatar",
    "abadmemunit":  "abadmemunit",
}
