CATALOG = {
    # ── Install methods ──────────────────────────────────────────────────
    "badupdate": {
        "name": "BadUpdate",
        "tab": "install",
        "type": "base",
        "desc": "Exploit original — descarga archivos de ABadAvatar sin payload libre",
        "dest": "BadUpdatePayload/",
        "author": "Grimdoomer",
    },
    "abadavatar": {
        "name": "ABadAvatar",
        "tab": "install",
        "type": "auto",
        "api_url": "https://api.github.com/repos/shutterbug2000/ABadAvatar/releases/latest",
        "fallback_url": "https://github.com/shutterbug2000/ABadAvatar/releases/download/vPB1.0/ABadAvatar-publicbeta1.0.zip",
        "asset_pattern": ".zip",
        "dest": "BadUpdatePayload/",
        "author": "shutterbug2000",
        "desc": "Requiere dashboard 17559 y datos de avatar instalados",
    },
    "badavatarhdd": {
        "name": "BadAvatarHDD",
        "tab": "install",
        "type": "auto",
        "api_url": "https://api.github.com/repos/shutterbug2000/ABadAvatar/releases/latest",
        "fallback_url": "https://github.com/shutterbug2000/ABadAvatar/releases/download/vPB1.0/ABadAvatar-publicbeta1.0.zip",
        "asset_pattern": ".zip",
        "dest": "BadUpdatePayload/",
        "author": "shutterbug2000",
        "desc": "Variante HDD — para consolas sin tarjeta de memoria",
    },
    "abadmemunit": {
        "name": "ABadMemUnit",
        "tab": "install",
        "type": "auto",
        "api_url": "https://api.github.com/repos/shutterbug2000/ABadMemUnit/releases/latest",
        "fallback_url": None,
        "asset_pattern": ".zip",
        "dest": "BadUpdatePayload/",
        "author": "shutterbug2000",
        "desc": "Alternativa si ABadAvatar no funciona en tu consola",
    },
    # ── Patches ──────────────────────────────────────────────────────────
    "xeunshackle": {
        "name": "XeUnshackle",
        "tab": "install",
        "type": "auto",
        "api_url": "https://api.github.com/repos/Byrom90/XeUnshackle/releases/latest",
        "fallback_url": "https://github.com/Byrom90/XeUnshackle/releases/download/v1.03/XeUnshackle-v1.03.zip",
        "asset_pattern": ".zip",
        "dest": "BadUpdatePayload/",
        "author": "Byrom90",
        "desc": "Más compatible con plugins y stealth servers",
    },
    "freemyxe": {
        "name": "FreeMyXe",
        "tab": "install",
        "type": "auto",
        "api_url": "https://api.github.com/repos/InvoxiPlayGames/FreeMyXe/releases/latest",
        "fallback_url": "https://github.com/InvoxiPlayGames/FreeMyXe/releases/download/v1.1/FreeMyXe-v1.1.zip",
        "asset_pattern": ".zip",
        "dest": "BadUpdatePayload/",
        "author": "InvoxiPlayGames",
        "desc": "Alternativa open-source a XeUnshackle",
    },
    # ── Dashboards ───────────────────────────────────────────────────────
    "aurora": {
        "name": "Aurora",
        "tab": "dashboards",
        "type": "manual",
        "url": "https://phoenix.xboxunity.net",
        "dest": "Apps/Aurora",
        "author": "Phoenix Team",
        "desc": "Dashboard más popular — descarga en phoenix.xboxunity.net",
        "color": "#107C10",
    },
    "freestyle": {
        "name": "Freestyle Dash",
        "tab": "dashboards",
        "type": "manual",
        "url": "https://github.com/xboxUnity/freestyle-dash",
        "dest": "Apps/FreestyleDash",
        "author": "xboxUnity",
        "desc": "Dashboard alternativo con soporte de skins",
        "color": "#1a3a6a",
    },
    "emerald": {
        "name": "Emerald",
        "tab": "dashboards",
        "type": "manual",
        "dest": "Apps/Emerald",
        "author": "Unknown",
        "desc": "Dashboard alternativo con interfaz minimalista",
        "color": "#1a6a3a",
    },
    "xexdash": {
        "name": "XeXDash",
        "tab": "dashboards",
        "type": "manual",
        "dest": "Apps/XeXDash",
        "author": "Unknown",
        "desc": "Dashboard clásico de la escena homebrew",
        "color": "#4a3a1a",
    },
    "xexloader": {
        "name": "XeXLoader",
        "tab": "dashboards",
        "type": "manual",
        "dest": "Apps/XeXLoader",
        "author": "Unknown",
        "desc": "Launcher simple de archivos XEX",
        "color": "#3a1a4a",
    },
    "ingeniouxd": {
        "name": "IngeniouX",
        "tab": "dashboards",
        "type": "manual",
        "dest": "Apps/IngeniouX",
        "author": "Unknown",
        "desc": "Dashboard moderno con interfaz actualizada",
        "color": "#1a4a6a",
    },
    "xenu": {
        "name": "Xenu",
        "tab": "dashboards",
        "type": "manual",
        "dest": "Apps/Xenu",
        "author": "Unknown",
        "desc": "Dashboard ultraminimalista para consolas RGH/JTAG",
        "color": "#3a3a3a",
    },
    "viper360": {
        "name": "Viper360",
        "tab": "dashboards",
        "type": "manual",
        "dest": "Apps/Viper360",
        "author": "Unknown",
        "desc": "Dashboard alternativo con gestor de juegos integrado",
        "color": "#6a1a1a",
    },
    # ── Homebrew ─────────────────────────────────────────────────────────
    "god_unlocker": {
        "name": "GOD Unlocker",
        "tab": "homebrew",
        "type": "manual",
        "dest": "Apps/GODUnlocker",
        "author": "Unknown",
        "desc": "Desbloquea archivos GOD de juegos instalados",
    },
    "xm360": {
        "name": "XM360",
        "tab": "homebrew",
        "type": "manual",
        "url": "https://github.com/xboxUnity/xm360",
        "dest": "Apps/XM360",
        "author": "xboxUnity",
        "desc": "Gestor de contenido multimedia para Xbox 360",
    },
    "ffplay": {
        "name": "FFPlay",
        "tab": "homebrew",
        "type": "manual",
        "dest": "Apps/FFPlay",
        "author": "Unknown",
        "desc": "Reproductor multimedia basado en FFmpeg",
    },
    "hddx_fixer": {
        "name": "HDDx Fixer",
        "tab": "homebrew",
        "type": "manual",
        "dest": "Apps/HDDxFixer",
        "author": "Unknown",
        "desc": "Herramienta de reparación y mantenimiento de HDD",
    },
    "xpg_chameleon": {
        "name": "XPG Chameleon",
        "tab": "homebrew",
        "type": "manual",
        "dest": "Apps/XPGChameleon",
        "author": "Unknown",
        "desc": "Gestor y editor de perfiles de jugador Xbox 360",
    },
    "xna_offline": {
        "name": "XNA Offline",
        "tab": "homebrew",
        "type": "manual",
        "dest": "Apps/XNAOffline",
        "author": "Unknown",
        "desc": "Soporte XNA para juegos indie sin conexión a internet",
    },
    "nxe2god": {
        "name": "NXE2GOD",
        "tab": "homebrew",
        "type": "manual",
        "dest": "Apps/NXE2GOD",
        "author": "Unknown",
        "desc": "Convierte instalaciones NXE al formato GOD rip",
    },
    "nand_flasher": {
        "name": "Simple 360 NAND Flasher",
        "tab": "homebrew",
        "type": "auto",
        "direct_url": "https://github.com/Swizzy/XDK_Projects/raw/master/Simple%20360%20NAND%20Flasher/Simple%20360%20NAND%20Flasher.zip",
        "asset_pattern": ".zip",
        "dest": "Apps/NANDFlasher",
        "author": "Swizzy",
        "desc": "Flasher NAND para consolas con hardware modificado",
    },
    "xell_launch": {
        "name": "Xell Launch",
        "tab": "homebrew",
        "type": "manual",
        "dest": "Apps/XellLaunch",
        "author": "Unknown",
        "desc": "Launcher de Xell desde la interfaz NXE",
    },
    # ── Stealth Servers ──────────────────────────────────────────────────
    "proto": {
        "name": "Proto",
        "tab": "stealth",
        "type": "manual",
        "free": True,
        "url": "https://freestealth.com",
        "dest": "Plugins/Proto",
        "author": "freestealth.com",
        "desc": "Red stealth GRATUITA — funciona con dashboard 17559",
        "log_hint": "Descarga cliente en freestealth.com → copia a USB/Plugins/Proto/ → configura en DashLaunch",
    },
    "xblghost": {
        "name": "xblGhost",
        "tab": "stealth",
        "type": "manual",
        "free": True,
        "url": "https://xblghost.live",
        "dest": "Plugins/xblGhost",
        "author": "xblghost.live",
        "desc": "Red stealth GRATUITA — compatible con dashboard 17559",
        "log_hint": "Descarga cliente en xblghost.live → copia a USB/Plugins/xblGhost/ → configura en DashLaunch",
    },
    "xbls": {
        "name": "XBLS",
        "tab": "stealth",
        "type": "manual",
        "free": False,
        "url": "https://www.xboxstealth.net",
        "dest": "Plugins/XBLS",
        "author": "xboxstealth.net",
        "desc": "Stealth server de pago — descarga cliente en xboxstealth.net",
        "log_hint": "Requiere suscripción en xboxstealth.net",
    },
    "cipher": {
        "name": "Cipher",
        "tab": "stealth",
        "type": "manual",
        "free": False,
        "dest": "Plugins/Cipher",
        "author": "Unknown",
        "desc": "Red stealth de pago — configuración manual del cliente",
        "log_hint": "Instala el cliente de Cipher en USB/Plugins/Cipher/ y configura en DashLaunch",
    },
    "xbguard": {
        "name": "XbGuard",
        "tab": "stealth",
        "type": "manual",
        "free": False,
        "url": "https://xbguard.live",
        "dest": "Plugins/XbGuard",
        "author": "xbguard.live",
        "desc": "Stealth server de pago — descarga cliente en xbguard.live",
        "log_hint": "Requiere suscripción en xbguard.live",
    },
    "xbnetwork": {
        "name": "XbNetwork",
        "tab": "stealth",
        "type": "manual",
        "free": False,
        "dest": "Plugins/XbNetwork",
        "author": "Unknown",
        "desc": "Red privada virtual de pago para Xbox 360 online",
        "log_hint": "Instala el cliente de XbNetwork en USB/Plugins/XbNetwork/ y configura en DashLaunch",
    },
    "nfinite": {
        "name": "Nfinite",
        "tab": "stealth",
        "type": "manual",
        "free": False,
        "dest": "Plugins/Nfinite",
        "author": "Unknown",
        "desc": "Servicio stealth de pago y alta seguridad",
        "log_hint": "Instala el cliente de Nfinite en USB/Plugins/Nfinite/ y configura en DashLaunch",
    },
    "tethered_live": {
        "name": "Tethered Live",
        "tab": "stealth",
        "type": "manual",
        "free": False,
        "dest": "Plugins/TetheredLive",
        "author": "Unknown",
        "desc": "Conecta tu Xbox a Live usando tu PC como proxy",
        "log_hint": "Instala el cliente de Tethered Live en USB/Plugins/TetheredLive/ y configura en DashLaunch",
    },
    "xbl_kyuubii": {
        "name": "XBL Kyuubii",
        "tab": "stealth",
        "type": "manual",
        "free": False,
        "dest": "Plugins/XBLKyuubii",
        "author": "Unknown",
        "desc": "Stealth alternativo de pago con cliente ligero",
        "log_hint": "Instala el cliente de XBL Kyuubii en USB/Plugins/XBLKyuubii/ y configura en DashLaunch",
    },
    # ── Plugins ──────────────────────────────────────────────────────────
    "general_plugins": {
        "name": "General Plugins",
        "tab": "plugins",
        "group": "Plugins",
        "type": "manual",
        "dest": "Plugins/General",
        "author": "Various",
        "desc": "Colección de plugins esenciales para Xbox 360",
    },
    "xbpirate": {
        "name": "xbPirate",
        "tab": "plugins",
        "group": "Plugins",
        "type": "manual",
        "dest": "Plugins/xbPirate",
        "author": "Unknown",
        "desc": "Plugin de gestión y descarga de contenido",
    },
    "hiddriver360": {
        "name": "hiddriver360",
        "tab": "plugins",
        "group": "Plugins",
        "type": "manual",
        "dest": "Plugins/hiddriver360",
        "author": "Unknown",
        "desc": "Driver HID personalizado para periféricos USB",
    },
    "hvp2": {
        "name": "HvP2",
        "tab": "plugins",
        "group": "Plugins",
        "type": "manual",
        "dest": "Plugins/HvP2",
        "author": "Unknown",
        "desc": "Parche del hipervisor v2 para funciones avanzadas",
    },
    "fakeanim": {
        "name": "FakeAnim V0.60",
        "tab": "plugins",
        "group": "Personalización",
        "type": "manual",
        "dest": "Plugins/FakeAnim",
        "author": "Unknown",
        "desc": "Personaliza las animaciones de arranque de la consola",
    },
    "x_notify": {
        "name": "X-Notify Pack",
        "tab": "plugins",
        "group": "Personalización",
        "type": "manual",
        "dest": "Plugins/XNotify",
        "author": "Unknown",
        "desc": "Pack de notificaciones personalizadas del sistema",
    },
    "boot_animation": {
        "name": "Boot Animation Pack",
        "tab": "plugins",
        "group": "Personalización",
        "type": "manual",
        "dest": "Plugins/BootAnimation",
        "author": "Unknown",
        "desc": "Colección de animaciones alternativas de arranque",
    },
    "xbox_one_xefu": {
        "name": "Xbox One Xefu Files",
        "tab": "plugins",
        "group": "Retrocompatibilidad",
        "type": "manual",
        "dest": "Compatibility/XboxOneXefu",
        "author": "Unknown",
        "desc": "Archivos XEFU de compatibilidad con Xbox One",
    },
    "hacked_compat": {
        "name": "Hacked Compatibility Files",
        "tab": "plugins",
        "group": "Retrocompatibilidad",
        "type": "manual",
        "dest": "Compatibility/HackedCompat",
        "author": "Unknown",
        "desc": "Archivos de retrocompatibilidad modificados",
    },
    "xefu_spoofer": {
        "name": "XEFU Spoofer V5",
        "tab": "plugins",
        "group": "Retrocompatibilidad",
        "type": "manual",
        "dest": "Compatibility/XEFUSpoofer",
        "author": "Unknown",
        "desc": "Spoofer de compatibilidad Xbox One v5",
    },
    "original_compat": {
        "name": "Original Compatibility Files",
        "tab": "plugins",
        "group": "Retrocompatibilidad",
        "type": "manual",
        "dest": "Compatibility/OriginalCompat",
        "author": "Unknown",
        "desc": "Archivos originales de retrocompatibilidad de Microsoft",
    },
}

# Method → effective download key mapping
METHOD_DL_MAP = {
    "badupdate":   "abadavatar",
    "badavatarhdd": "abadavatar",
    "abadavatar":  "abadavatar",
    "abadmemunit": "abadmemunit",
}
